# Generated by Django 4.2.4 on 2023-11-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diettracker', '0002_consume_delete_consumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
    ]
